version: '2.4'
services:
    rsu:
        hostname: rsu
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        volumes:
          - ./deployments/atcll/config-rsu.ini:/config.ini
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=1
            - VANETZA_STATION_TYPE=15
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:01
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.10

    obu_ambulance:
        hostname: obu_ambulance
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        volumes:
          - ./deployments/atcll/config-obu.ini:/config.ini
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=2
            - VANETZA_STATION_TYPE=10
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:02
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.20

    obu_normal:
        hostname: obu_normal
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        volumes:
          - ./deployments/atcll/config-obu.ini:/config.ini
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=3
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:02
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.30
networks:
  vanetzalan0:
    external: true